apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: yhk0v8ub7-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe-go:github-75fadc1e81516c998877c2bdf0ffe1337544edba
          name: container-image
